export const routes = {
  home: '/',
  feed: '/feed',
  search: '/',
  articles: '/articles',
  articleNew: '/articles/new',
  article: (slug: string) => `/articles/${encodeURIComponent(slug)}`,
  articleEdit: (id: string) => `/articles/${encodeURIComponent(id)}/edit`,
  news: '/news',
  newsDetail: (slug: string) => `/news/${encodeURIComponent(slug)}`,
  newsNew: '/news/new',
  newsSuggest: '/news/suggest',
  newsEdit: (id: string) => `/news/${encodeURIComponent(id)}/edit`,
  resources: '/resources',
  resourceNew: '/resources/new',
  resourceSuggest: '/resources/submit',
  resourceEdit: (id: string) => `/resources/${encodeURIComponent(id)}/edit`,
  projects: '/projects',
  projectNew: '/projects/new',
  project: (key: string) => `/projects/${encodeURIComponent(key)}`,
  questions: '/questions',
  questionNew: '/questions/new',
  question: (id: string) => `/questions/${encodeURIComponent(id)}`,
  jobs: '/jobs',
  jobNew: '/jobs/new',
  job: (id: string) => `/jobs/${encodeURIComponent(id)}`,
  events: '/events',
  event: (slug: string) => `/events/${encodeURIComponent(slug)}`,
  eventNew: '/events/new',
  searchByTag: (slug: string) => `/?tags=${encodeURIComponent(slug)}`,
  tools: '/tools',
  cheatsheets: '/cheatsheets',
  cheatsheet: (slug: string) => `/cheatsheets/${slug.split('/').map(encodeURIComponent).join('/')}`,
  roadmaps: '/roadmaps',
  roadmap: (slug: string) => `/roadmaps/${encodeURIComponent(slug)}`,
  codex: '/codex',
  organizations: '/organizations',
  organizationNew: '/organizations/new',
  organization: (slug: string) => `/organizations/${encodeURIComponent(slug)}`,
  organizationSettings: (slug: string) => `/organizations/${encodeURIComponent(slug)}/settings`,
  profile: (username: string) => `/profile/${encodeURIComponent(username)}`,
  about: '/about',
  faq: '/faq',
  sponsors: '/sponsors',
  contribute: '/contribute',
  contact: '/contact',
  guidelines: '/guidelines',
  terms: '/terms',
  privacy: '/privacy',
  rss: { articles: '/rss/articles.xml', news: '/rss/news.xml' },
  auth: {
    signIn: '/login',
    signUp: '/signup',
    forgotPassword: '/forgot-password',
    accountRecovery: '/auth/account-recovery',
  },
  account: {
    root: '/account',
    danger: '/account/danger',
    activity: '/account/activity/comments',
    profile: '/account/profile',
    articles: '/account/content/articles',
    projects: '/account/content/projects',
    organizations: '/account/organizations',
    questions: '/account/content/questions',
    answers: '/account/content/answers',
    project: (id: string) => `/account/projects/${encodeURIComponent(id)}/edit`,
    jobs: '/account/content/jobs',
    job: (id: string) => `/account/jobs/${encodeURIComponent(id)}/edit`,
    resourceSuggestions: '/account/contributions/resources',
    newsSuggestions: '/account/contributions/news',
    eventSuggestions: '/account/contributions/events',
    jobSuggestions: '/account/contributions/jobs',
    notifications: '/account/interactions/notifications',
    votes: '/account/interactions/votes',
    views: '/account/interactions/views',
    following: '/account/interactions/following',
    bookmarks: '/account/interactions/bookmarks',
    comments: '/account/interactions/comments',
    sessions: '/account/security/sessions',
    emails: '/account/security/emails',
    passkeys: '/account/security/passkeys',
    password: '/account/security/password',
    security: '/account/security',
    providers: '/account/security/connections',
    preferences: '/account/preferences',
  },
  panel: {
    root: '/panel',
    articles: '/panel/articles',
    news: '/panel/news',
    newsSuggestions: '/panel/news/suggestions',
    events: '/panel/events',
    eventSuggestions: '/panel/events/suggestions',
    resources: '/panel/resources',
    resourceSuggestions: '/panel/resources/suggestions',
    questions: '/panel/questions',
    projects: '/panel/projects',
    jobs: '/panel/jobs',
    jobSuggestions: '/panel/jobs/suggestions',
    feedback: '/panel/feedback',
    comments: '/panel/comments',
    hidden: '/panel/hidden',
    reports: '/panel/reports',
    status: '/panel/status',
    users: '/panel/users',
    user: (id: string) => `/panel/users/${encodeURIComponent(id)}`,
    tags: '/panel/tags',
    roles: '/panel/roles',
  },
} as const;
